[workspace]

members = [
	"dataplane",
	"dpdk",
	"dpdk-sys",
	"dpdk-sysroot-helper",
	"errno",
	"id",
	"net",
	"pipeline",
	"routing",
]

default-members = [
	"dataplane",
	"dpdk-sysroot-helper",
	"errno",
	"id",
	"net",
	"pipeline",
	"routing",
]

resolver = "3"

[workspace.dependencies]

# Internal
dpdk = { path = "./dpdk" }
dpdk-sys = { path = "./dpdk-sys" }
dpdk-sysroot-helper = { path = "./dpdk-sysroot-helper" }
dplane-rpc = { git = "https://github.com/githedgehog/dplane-rpc.git", version = "1.0.0" }
errno = { path = "./errno", package = "dataplane-errno" }
id = { path = "./id", package = "dataplane-id" }
net = { path = "./net", features = ["test_buffer"]}
pipeline = { path = "./pipeline" }
routing = { path = "./routing" }

# External
ahash = { version = "0.8.11", default-features = false, features = [] }
arbitrary = { version = "1.4.1", default-features = false, features = [] }
arc-swap = { version = "1.7.1" , default-features = false, features = [] }
arrayvec = { version = "0.7.6", default-features = false, features = [] }
bindgen = { version = "0.71.1", default-features = false, features = [] }
bolero = { version = "0.13.0", default-features = false, features = [] }
bytes = { version = "1.10.1", default-features = false, features = [] }
clap = { version = "4.5.32", default-features = true, features = [] }
ctrlc = { version = "3.4.5", default-features = false, features = [] }
derive_builder = { version = "0.20.2", default-features = false, features = ["default"] }
doxygen-rs = { version = "0.4.2", default-features = false, features = [] }
dyn-iter = { version = "1.0.1", default-features = false, features = [] }
etherparse = { version = "0.17.0", default-features = false, features = [] }
ordermap = { version = "0.5.6", default-features = false, features = [] }
ipnet = { version = "2.11.0", default-features = false, features = [] }
iptrie = { version = "0.10.2", default-features = false, features = [] }
mio = { version = "1.0.3", default-features = false, features = [] }
nom = { version = "7.1.3", default-features = false, features = [] }
serde = { version = "1.0.219", default-features = false, features = [] }
serde_yml = { version = "0.0.12", default-features = false, features = [] }
thiserror = { version = "2.0.12", default-features = false, features = [] }
tracing = { version = "0.1.41", default-features = false, features = ["attributes"] }
tracing-subscriber = { version = "0.3.19", default-features = false, features = [] }
tracing-test = { version = "0.2.5", default-features = false, features = [] }
uuid = { version = "1.16.0", default-features = false, features = [] }

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"

[profile.fuzz]
inherits = "release"
opt-level = 3
panic = "unwind"
debug = "full"
lto = "off"
debug-assertions = true
overflow-checks = true
codegen-units = 1
rpath = true
