[package]
name = "dataplane"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]

ctrlc = { workspace = true, features = ["termination"] }
net = { workspace = true }
dpdk = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["default"] }
