name: Build and deploy docs
on:
  pull_request:
    paths:
      - '*.nix'
      - 'design-docs/**'
      - 'nix/**'
      - '.github/workflows/build-and-deploy-docs.yml'
  push:
    branches:
      - 'main'
    paths:
      - '*.nix'
      - 'design-docs/**'
      - 'nix/**'
      - '.github/workflows/build-and-deploy-docs.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: read
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Extract git hash
        shell: bash
        run: echo "git_hash=${GITHUB_SHA}" >> $GITHUB_OUTPUT
        id: extract_hash

      - name: Install nix
        uses: cachix/install-nix-action@v27

      - name: Nix cache
        id: cache-nix-packages
        uses: actions/cache@v4
        with:
          path: ~/work/nix-store
          key: cache-nix-${{ runner.os }}-${{ hashFiles('./flake.lock') }}

      - name: Build design docs
        run: |
          mkdir --parent ~/work/nix-store
          mkdir --parent ~/work/out
          nix build '#design-docs' --store ~/work/nix-store --out-link ~/work/out/design-docs

      - name: Copy design doc build to publish directory
        run: |
          set -euxo pipefail
          mkdir --parent ${{ github.workspace }}/publish/
          cp -r ~/work/nix-store/nix/store/"$(basename "$(readlink ~/work/out/design-docs)")" ${{ github.workspace }}/publish/design-docs

      - name: (Push) Setup Pages
        if: ${{ !github.event.pull_request }}
        uses: actions/configure-pages@v5

      - name: (Push) Upload design-docs
        if: ${{ !github.event.pull_request }}
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload design-docs build directory content
          path: 'publish/design-docs'

      - name: (Push) Deploy to GitHub Pages
        if: ${{ !github.event.pull_request }}
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: (PR) Deploy documentation preview
        if: ${{ github.event.pull_request }}
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ${{ github.workspace }}/publish/design-docs
          alias: preview-${{ github.event.number }}
          deploy-message: ${{ github.event.pull_request.title }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fails-without-credentials: true
          enable-commit-status: true
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-github-deployment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 5
